name: promptlens
packages:
  - "core/*"
command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  build: "echo 'No mobile build needed - using Tauri for all platforms'"
  analyze: "echo 'No mobile analysis needed - using Tauri for all platforms'"
