[package]
name = "pl-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { workspace = true }
webp = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }


